# Generated by Django 3.2.7 on 2021-09-04 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_category',
        ),
        migrations.AddField(
            model_name='images',
            name='image_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='images.category'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='images',
            name='image_location',
        ),
        migrations.AddField(
            model_name='images',
            name='image_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='images.location'),
            preserve_default=False,
        ),
    ]
