# Generated by Django 3.2.7 on 2021-09-04 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='images.category'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='images.location'),
        ),
    ]
